### ISSUE TITLE
Document getting started for new users

### ISSUE THREAD

**Issue by mikelynch** [rocm-arch/rocm-arch#102]
Thank you everyone who's contributing to getting ROCm running on Arch! Obviously there are a lot of packages here. Please could someone document the good starting points to get
1. A basic ROCm setup working (e.g. that you could then run a docker image on top of with the userspace components), and
2. Ideally what's needed to get tensorflow for ROCm running bare metal?

I've been having some issues where `hip` and `hip-hcc` say they are mutually incompatible, and subsequent installation attempts want to remove the last attempted one (I'm running latest Arch with the latest stable kernel – `5.6.2`)

**Comment by acxz** [comment]
Thx for your comments!

The packages here are still a WIP, but our end goal is to follow upstream as close as possible. As such for first point I would refer you to the official documentation: https://rocm-documentation.readthedocs.io/en/latest/

For the second point I haven't personally looked at tensorflow yet, but feel free to make a package request issue, so we can track and others can try to tackle it.

For your hip / hip-hcc issue it would be best if you make another issue for that as well.

Again many of the packages are a WIP but our ultimate goal is to follow the same package structure and pipeline as AMD's Ubuntu/CentOS packages so that users can look at the official documentation.

**Comment by acxz** [comment]
Closing this issue as I believe it has been answered.
