### ISSUE TITLE
[(python-)tensorflow-rocm] Tensorflow complains "libmcwamp.so.3" not found.

### ISSUE THREAD

**Issue by notcome** [rocm-arch/rocm-arch#126]
First of all, thanks for everyone's work. This is really a huge amount of packages to deal with.

I did my best try to install `rocm-dev` manually, after which I installed `tensorflow-rocm` via pip using Anaconda. However, when I tried to list devices via Tensorflow, it complained that it could no t find `libmcwamp.so.3`.

The fix is simple, by `find` I found that the relevant library is inside `/opt/rocm/hcc/lib/`. Adding it to `LD_LIBRARY_PATH` solves the issue. However, I would assume things would work out-of-box. So is this some package description error that should be fixed ?

PS: I am not familiar with Linux, so my understanding of library search path and package manager could be wrong…

**Comment by acxz** [comment]
Thanks for your words, means a lot!

I believe the problem boils down to symlinking the files in /oot/rocm/hcc/lib to the proper places. Right now getting tensorflow to work is not a huge priority for us, since we are still trying to get rocm-dev and rocm-libs to build in clean chroots for creating binaries. Once we accomplish that, steps moving forward could include packaging `python-tensorflow-rocm` and `python-pytorch-rocm`. 
Thx for the report though, I am sure it will help whoever ends up packaging tensorflow-rocm on the AUR, or better yet you can try to submit a PR to add the proper symlink so that the pip package works right off the bat.

**Comment by notcome** [comment]
Thanks for the comments.

My ultimate goal is to get PyTorch to work, which seems already done by @s-bernard . My attempt to run Tensorflow shows that I need MIOpen, for which I was stuck due to getting rocBLAS to compile with Tensile.

I will try @s-bernard 's pull requests in a clean environment. If that works and the issue is resolved after those patches, I would close this. Otherwise I will see if I could get pull request done. Right now, I am messed up with old PKGBUILD files on AUR server and new ones in this repo. A clean environment with latest PKGBUILD files might solve the issue already.

**Comment by acxz** [comment]
Yeah that is understandable, we need to get some packages synced to the AUR ASAP, but since you are developing on the PKGBUILDs, I recommend you base your work off of the PKGBUILDs in the master repo of this branch instead of the ones on the AUR. At least until the syncs happen.

**Comment by tpkessler** [comment]
`libmcwamp.so` is part of `hcc` which is deprecated and removed from this repo and the AUR.
