### ISSUE TITLE
[rocm-opencl-runtime] z3 is not a direct dependency

### ISSUE THREAD

**Issue by kozross** [rocm-arch/rocm-arch#148]
While it _is_ a dependency of ``llvm-amdgpu``, ``z3`` is not a direct dependency. Without it, OpenCL will not work (even ``clinfo`` will crash).

**Comment by kode54** [comment]
It should be a direct dependency of `comgr`, since that is the nearest library which imports it.

**Comment by kozross** [comment]
According to #128, a clean rebuild of ``rocm-opencl-runtime`` gave the following output:

```
==> Packages no longer required by any installed package:
       llvm-amdgpu llvm-roc rocm-cmake rocm-device-libs
```

Removing those also took out ``z3``. Also, issue #147 appears to run afoul of something similar.

**Comment by kode54** [comment]
I was stating the place where it should be added as a direct dependency. I checked all libraries under `/opt/rocm`, and only the `comgr` library imports `z3`. Presumably because it static linked parts of llvm-amdgpu which also required this library.

I am only in a position to fork and file a pull request, so you'll have to wait for the repository to apply any particular solution.

**Comment by ranisalt** [comment]
You are right. I removed the `llvm-amdgpu` package together with `z3` and `clinfo` broke. Then, I installed `z3` and it worked again, even without `llvm-amdgpu`.

**Comment by ranisalt** [comment]
Please update `comgr` and report back.

**Comment by kozross** [comment]
Seems to be fixed now - ``z3`` is now pinned to ``comgr`` and can't be removed without also removing ``comgr``.

**Comment by ranisalt** [comment]
@kozross I also learned that comgr requires z3 at runtime, and is linked against it, so it was a mistake.
