### ISSUE TITLE
[rock-dkms/rock-dkms-git] Get ROCk to build from upstream's source

### ISSUE THREAD

**Issue by neeshy** [rocm-arch/rocm-arch#29]
Instead of taking from the Debian sources.
See: https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/master/drivers/gpu/drm/amd/dkms/Makefile

This way rock-dkms-git can actually pull from git sources, instead of being a duplicate of rock-dkms.

**Comment by rigred** [comment]
What's the current state of this issue?
Last  checked we have a working open source implementation of ROCk inside the open source amdgpu kernel module in the form of KFD (Kernel Fusion Device)
This means the ROCk module provided upstream is only for older kernels on LTS ubuntu etc distros.
For arch even the LTS branch already includes KFD since August 2018

See
https://github.com/torvalds/linux/tree/master/drivers/gpu/drm/amd/amdkfd
https://www.phoronix.com/scan.php?page=news_item&px=AMDKFD-Merge-Into-AMDGPU
https://lists.freedesktop.org/archives/amd-gfx/2018-August/025719.html

Suggest we remove rock-dkms entirely as it bears no significance to Arch.

rocminfo and all rocm applications happily detect and work with the `/dev/kfd` device
![image](https://user-images.githubusercontent.com/5716332/80028377-549a5880-84e5-11ea-92e9-264d7c681944.png)

**Comment by neeshy** [comment]
>Suggest we remove rock-dkms entirely as it bears no significance to Arch.
I think that's the best way to go. rock-dkms doesn't even build on kernels past version 5.0 IIRC.

**Comment by rigred** [comment]
Here's a table that currently lists the ROCK-dkms vs KFD in kernel Pro's Con's
Some of these have changed since
https://github.com/RadeonOpenCompute/ROCm#rocm-support-in-upstream-linux-kernels

**Comment by acxz** [comment]
Closing this issue since no work has been done on it. If someone can build from source, they are free to create the `rock-dkms` package and create a PR for it in this repo.
