### ISSUE TITLE
[rocrand] can't build

### ISSUE THREAD

**Issue by fernandoblalves** [rocm-arch/rocm-arch#303]
Hi all,

My guess is that it's missing the `HIP ROOT` and `BUILD_SHARED_LIBS` variables, I tried exporting them but weren't read. The full output can be read [here](https://pastebin.com/iQCxu6qa).

**Comment by acxz** [comment]
hmm haven't seen that error before. Can you try installing in a clean chroot? https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot#Convenience_way

For an easier way to use clean chroot with arch4edu (since you will need many deps) refer to this comment: https://github.com/rocm-arch/rocm-arch/issues/168#issuecomment-629389272

**Comment by fernandoblalves** [comment]
Weird, indeed it installs without issues using `arch4edu-x86_64-build`.
