### ISSUE TITLE
[rocm-dbgapi] Update to new release

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#344]

**Comment by naetherm** [comment]
Closed with https://github.com/rocm-arch/rocm-arch/commit/3871acaf7fbc30ff4aee2291a7b23ff9cf3fd954

**Comment by acxz** [comment]
reopening because still not pushed to the AUR 
Also @naetherm please read the [contributing guidelines](https://github.com/rocm-arch/rocm-arch#contributing). It would be nice if you can open PRs before you get more comfortable with pushing to the AUR. 

It is important to create the .SRCINFO. See: https://wiki.archlinux.org/index.php/.SRCINFO

**Comment by naetherm** [comment]
> reopening because still not pushed to the AUR
> Also @naetherm please read the [contributing guidelines](https://github.com/rocm-arch/rocm-arch#contributing). It would be nice if you can open PRs before you get more comfortable with pushing to the AUR.
> 
> It is important to create the .SRCINFO. See: https://wiki.archlinux.org/index.php/.SRCINFO

Uh, of course. Don't know what went wrong, I will push the corresponding .SRCINFOs, sorry for that!

**Comment by acxz** [comment]
I fixed rocm-opencl-runtime, I'll let you fix up dbgapi and debug-agent.

**Comment by naetherm** [comment]
Fix  rocm-dbgapi and rocm-gdb.

**Comment by acxz** [comment]
thank you but again would have preferred a PR first: https://github.com/rocm-arch/rocm-arch/commit/0bf180f9c458c27d93262d9ebc28545a2c4d9539

Also can you explain the merge commit here: https://github.com/rocm-arch/rocm-arch/commit/bfecf36f656f66adcd23b57876050dd2b1d30c1b

**Comment by naetherm** [comment]
> thank you but again would have preferred a PR first: [0bf180f](https://github.com/rocm-arch/rocm-arch/commit/0bf180f9c458c27d93262d9ebc28545a2c4d9539)

Sorry for that, I've thought - due to the already commited changeset - I'll add the fixed directly.

> Also can you explain the merge commit here: [bfecf36](https://github.com/rocm-arch/rocm-arch/commit/bfecf36f656f66adcd23b57876050dd2b1d30c1b)

If you mean the commit message: I know that's very unintuitive, in other projects I am part of that one should be used for merging with incoming changes. Is there a preferred way of commenting merges if the automatic one fails?

**Comment by acxz** [comment]
I don't see a reason for the merge commit at all is what I was thinking. I believe you should have rebased origin master onto your local branch instead of a merge. In any case I think it is fine, in the sense that it shouldn't mess up with the AUR syncing.

Speaking of the AUR syncing will you doing that or should I?
Just a `aurpublish <package_name>` should do the trick.

**Comment by naetherm** [comment]
> Speaking of the AUR syncing will you doing that or should I?
> Just a `aurpublish <package_name>` should do the trick.

Will do that now.

**Comment by acxz** [comment]
got it
