### ISSUE TITLE
[rocm-gdb] Update to new release

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#349]

**Comment by naetherm** [comment]
Closed with https://github.com/rocm-arch/rocm-arch/commit/1e21461b458c15588e1b19e8b837fa2ca57f78bb

**Comment by acxz** [comment]
reopening because still not pushed to the AUR 
Also @naetherm please read the [contributing guidelines](https://github.com/rocm-arch/rocm-arch#contributing). It would be nice if you can open PRs before you get more comfortable with pushing to the AUR. 

It is important to create the .SRCINFO. See: https://wiki.archlinux.org/index.php/.SRCINFO

**Comment by acxz** [comment]
synced
