### ISSUE TITLE
[rocsparse] fortran build error

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#383]
From: @tpkessler 
> With 3.7.0, rocsparse has introduced a fortran interface. However, the code does not compile with newer gfortran versions. Relevent upstream PR: ROCmSoftwarePlatform/rocSPARSE#210

**Comment by neoabs** [comment]
Same:

`[ 97%] Built target rocsparse_fortran
Call parameter type does not match function signature!
  %StackGuardSlot = alloca i8*, addrspace(5)
 i8**  call void @llvm.stackprotector(i8* %24, i8* addrspace(5)* %StackGuardSlot)
in function _Z41csrgemm_fill_block_per_row_device_pointerI21rocsparse_complex_numIdELj128ELj16ELj256ELj137EEviPKiS3_PKT_S3_S3_S6_S3_S3_S6_S6_S3_S3_S6_S3_PiPS4_21rocsparse_index_base_S9_S9_S9_bb
LLVM ERROR: Broken function found, compilation aborted!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/rocm/llvm/bin/llc /tmp/rocsparse_csrgemm-a9281b-gfx803-optimized-3562d7.bc -O3 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx803 -filetype=obj -amdgpu-early-inline-all=true -amdgpu-function-calls=false -o /tmp/rocsparse_csrgemm-a9281b-gfx803-52822a.o 
1.	Running pass 'CallGraph Pass Manager' on module '/tmp/rocsparse_csrgemm-a9281b-gfx803-optimized-3562d7.bc'.
2.	Running pass 'Module Verifier' on function '@_Z41csrgemm_fill_block_per_row_device_pointerI21rocsparse_complex_numIdELj128ELj16ELj256ELj137EEviPKiS3_PKT_S3_S3_S6_S3_S3_S6_S6_S3_S3_S6_S3_PiPS4_21rocsparse_index_base_S9_S9_S9_bb'
 #0 0x000055c30907bccb llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/rocm/llvm/bin/llc+0x1924ccb)
 #1 0x000055c309079884 llvm::sys::RunSignalHandlers() (/opt/rocm/llvm/bin/llc+0x1922884)
 #2 0x000055c3090799d9 (/opt/rocm/llvm/bin/llc+0x19229d9)
 #3 0x00007efe536c3960 __restore_rt (/usr/lib/libpthread.so.0+0x14960)
 #4 0x00007efe53155355 raise (/usr/lib/libc.so.6+0x3c355)
 #5 0x00007efe5313e853 abort (/usr/lib/libc.so.6+0x25853)
 #6 0x000055c308ff9284 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/rocm/llvm/bin/llc+0x18a2284)
 #7 0x000055c308ff93a9 (/opt/rocm/llvm/bin/llc+0x18a23a9)
 #8 0x000055c3089cae98 (/opt/rocm/llvm/bin/llc+0x1273e98)
 #9 0x000055c3089430c0 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/rocm/llvm/bin/llc+0x11ec0c0)
#10 0x000055c3081d7371 (/opt/rocm/llvm/bin/llc+0xa80371)
#11 0x000055c308944a70 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/rocm/llvm/bin/llc+0x11eda70)
#12 0x000055c307b92e9d main (/opt/rocm/llvm/bin/llc+0x43be9d)
#13 0x00007efe53140002 __libc_start_main (/usr/lib/libc.so.6+0x27002)
#14 0x000055c307bf0d1e _start (/opt/rocm/llvm/bin/llc+0x499d1e)
clang-11: error: unable to execute command: Aborted (core dumped)
clang-11: error: amdgcn-link command failed due to signal (use -v to see invocation)
clang version 11.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 49b61be7b403dde329e3f52c996e6cd5de81a485)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [library/CMakeFiles/rocsparse.dir/build.make:368: library/CMakeFiles/rocsparse.dir/src/extra/rocsparse_csrgemm.cpp.o] Error 254
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:115: library/CMakeFiles/rocsparse.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

`gcc-fortran                                                                                                                                            [Installed] 10.1.0-2 `

**Comment by tpkessler** [comment]
It's not the same. The fortran interface is compiled at the very beginning but your error appears at 97%. It's a compiler bug:
> LLVM ERROR: Broken function found, compilation aborted!
> PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.

**Comment by tpkessler** [comment]
My patch was merged upstream. We can remove the patch with the next ROCm release.

**Comment by acxz** [comment]
The original fortran issue has been resolved with 56891344cccb3410a0f714f77c158b59a16a2b6d

@neoabs if you are still encountering issues please open another issue.
