### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#44]
I would like to thank you for your fantastic work! It's the first time (ROCm 3.1) I'm able to compile nearly all packages. Keep up your great work.

**Comment by acxz** [comment]
Thanks so much! Really hope we as a community can get this boi up and running. Let's take down NVIDIA lol.

Unfortunately, I will have to close this issue since it not really an issue. But thank you, really means a lot when people recognize other's hard work. Esp when its out of their own good will.
