### ISSUE TITLE
[rocm-dkms] Cannot  install due to missing openmp-extras

### ISSUE THREAD

**Issue by Houkime** [rocm-arch/rocm-arch#471]
Because `rocm-dkms` depends on the **whole** metapackage `rocm-dev`, nonexistence of `openmp-extras` in AUR or nonexistence or failure to build of __any__ other extra package added to `rocm-dev` results in failing installation regardless of whether installation is actually possible or not.

```
$ yay -S rocm-dkms 
 -> Could not find all required packages:
	openmp-extras (Wanted by: rocm-dkms -> rocm-dev)
```

Proposed solution: `rocm-dkms` should NOT depend on the whole `rocm-dev`, but rather on the packages that are actually required to build and run it.  
Either that or `rocm-dev` should be redefined as a minimal set of rocm packages needed for `rocm-dkms`.  
Hope it makes sense.

**Comment by acxz** [comment]
Hello @Houkime you bring up valid concerns, but let me clarify some things.
(I should prob put this in the FAQ section of our readme.)

1. `rocm-dkms` is only needed for LTS kernels
2. The deb package of `rocm-dkms` provided by upstream AMD depends on `rocm-dev` hence we depend on `rocm-dev`
3. We have set `rocm-dev` to depend on the packages as the upstream deb package states

For dependency issues you should post at the upstream ROCm repo.

I realize that upgrading `rocm-dev` may not have been the right move for users.
In any case the actual issue here is `openmp-extras` does not exist, which is being tracked by #463

**Comment by Hufschmidt** [comment]
**Side question:**

> 1. `rocm-dkms` is only needed for LTS kernels

Do you mean by that, that the dkms-package is only available/supported for the current LTS kernel(s) (eg. 5.4) by AMD or that it is required for the LTS kernel(s), but has already been mainlined for current kernel (eg. 5.9) release(s)?

**Comment by acxz** [comment]
The `dkms` package is available for any kernel, it just wont work for the non-LTS kernels. AMD themselves only support it for the LTS. I'm not sure about whether `dkms` is required for LTS per se. But if you want to use `rocm` on the later kernel releases the support for it is already in newer kernels.

The AMD documentation prob does the best job explaining it:
https://github.com/RadeonOpenCompute/ROCm#rocm-support-in-upstream-linux-kernels

**Comment by acxz** [comment]
I went ahead and created the boiler plate openmp-extras package, to prevent build errors.
