### ISSUE TITLE
[roctracer] build error:     hip_ostream_ops.h: No such file or directory

### ISSUE THREAD

**Issue by ErnestKz** [rocm-arch/rocm-arch#508]
Disclaimer: I'm quite a noob at linux, especially package managemnt and building libraries.   
   
I used the command `yay -S tensorflow-rocm` and after good while of building, ran into a build error.      
   
After deducing which package seemed to be causing the error, `roctracer`, I ran `yay -S roctracer`. This gave me
a similar looking error to the initial one:    

https://gist.github.com/ErnestKz/a55ebc09f21db3a781ed2278e2791012

**Comment by acxz** [comment]
roctracer binary is available on arch4edu (see readme) so you can install it from there for now, if you can't build it. We only recommend people building the packages if they are developing/contributing to this repo. In fact tensorflow-rocm is also on arch4edu.

I'll leave this issue open for a week to see if others experience the issue, and if not I'll go ahead and close it.
Feel free to close it on your own if you get the arch4edu binary working.

**Comment by tpkessler** [comment]
> After deducing which package seemed to be causing the error, roctracer

`python` complains that it cannot find `cppheaderparser`. Which python version do you have installed? Are there multiple installations (like anaconda,...)?

**Comment by ErnestKz** [comment]
I have multiple versions of python installed. On the system I had python 3.9.0 installed. But once I found out tensorflow doesn't support it, I installed pyenv to be able to change versions, and then installed python 3.6.0 via pyenv, then once I found out jupyter doesn't support python 3.6.0, I installed python 3.7.5.  I also used venv to install some of the packages associated with each python version with pip, but on some pip installs I forgot to activate the venv, so some packages for some versions are installed globally.    
   
When I ran into the building problems I must've been on python 3.6.0.   

`[ek@Station ~]$ pyenv versions
  system
* 3.6.0 (set by /home/ek/.pyenv/version)
  3.7.5`


Right now, I tried running 'yay -S roctracer` with each of the different python versions activated.

Seems like the errors are the same; Python 3.7.5:
https://gist.github.com/ErnestKz/d3336b923f7fa64f61dcb3eea43c87e8

Python 3.9:
https://gist.github.com/ErnestKz/412ccfbb5016f99536d8e5e557eaf6f3 
    
I havent tried reinstalling other packages with different python versions as I don't really understand how the package manager manges the python packages for different versions of python, possibly its a big mess, and possbly quite a big time sink.    
   
I'll try out building from arch4edu.

**Comment by tpkessler** [comment]
Let me explain the way `yay` works. The package `python-cppheaderparser` (which provides the CppHeaderParser module for python) installs the files to the path corresponding to the python version package was built with. With python from the arch repos, this is `/usr/lib/python3.9/site-packages` at the moment. If you run `yay` as a normal user (not a clean chroot), that python version is picked which first appears in your PATH. Depending on your configuration, this may any of those python versions you mentioned. Now, `python-cppheaderparser` was successfully built by `yay` and is installed to some path on your computer. When building `roctracer`, `yay` (actually `makepkg`) checks for the requirement and sees that `python-cppheaderparser` is installed. It does not check for the python version with which the package was built! During the build phase, `cmake` is called and looks for a python installation. Because it has its own search paths, it may not find the python version that was used for `python-cppheaderparser`. This causes your problem.
There are several options:

* Uninstall all python versions except for one and rebuild (most of) the ROCm stack,
* Make sure that only one python version is used throughout the build procedure (maybe impossible)
* Use the binary packages from arch4edu. They are built against python 3.9, so I don't know if `tensorflow-rocm` works with that version. Did you encounter any problems @acxz ?

**Comment by ErnestKz** [comment]
Thank for that insight.  

 I installed roctrancer from arch4edu and the command completed without issue.   
  
I was then able to finish the install of tensorflow-rocm.   
 
Thank you all!

Now I just need to figure out how to use it with tensorflow

**Comment by acxz** [comment]
> They are built against python 3.9, so I don't know if tensorflow-rocm works with that version. Did you encounter any problems @acxz ?

I haven't tried tensorflow in a long time, either from the AUR or from the pip package, so I can't say. I think it should be fine no matter which python version you use, although not sure how well py39 has been tested upstream.

> Now I just need to figure out how to use it with tensorflow

tensorflow-rocm, whether the AUR package or the pip package should be able to find roctracer automatically.

Glad you got it to work!
