### ISSUE TITLE
[rocm-utils] depends on rocm-clang-ocl instead of clang-ocl

### ISSUE THREAD

**Issue by rigred** [rocm-arch/rocm-arch#51]
Am I correct in thinking this is not correct?
It should be changed to clang-ocl as I understand. 

https://github.com/rocm-arch/rocm-arch/blob/master/rocm-utils/PKGBUILD

**Comment by acxz** [comment]
According to [upstream](https://github.com/RadeonOpenCompute/ROCm#rocm-binary-package-structure) package structure, `rocm-utils` is a meta package / group that contains `rocminfo` and 
`rocm-clang-ocl`. We should keep it `rocm-clang-ocl`.

**Comment by rigred** [comment]
Hmm
Currently rocm-clang-ocl is a broken outdated mess on the AUR. 

I've updated a private PKGBUILD to build it but directories mismatch as clang-ocl bin expects /opt/rocm-3.1.0 paths in various hardcoded locations. 

It also seems that clang-ocl binaries and rocm-clang-ocl binares are meant to be the same thing
So I would remove the rocm-clang-ocl and change it to clang-ocl

**Comment by acxz** [comment]
I have submitted an orphan request for `rocm-clang-ocl` so we should be able to adopt it soon. I would like to follow upstream as much as possible since if users have issues or concerns they can refer to upstream documentation instead trying to figure out what "Arch" did differently. Let's be patience, I can try to expedite the orphan process by talking to some TUs as well.

**Comment by acxz** [comment]
Going ahead and closing this issue, see #11 to track the inclusion of rocm-clang-ocl from @whoisroot
