### ISSUE TITLE
Change install to versioned directory path

### ISSUE THREAD

**Issue by rigred** [rocm-arch/rocm-arch#52]
https://rocm-documentation.readthedocs.io/en/latest/Current_Release_Notes/Current-Release-Notes.html#before-you-begin

Please see above first ^^

Currently this project is still using the `/opt/rocm` directory structure while upstream has changed to using a versioned path of `/opt/rocm-3.1.0` as an example. 

I've noticed that several of the upstream code snippets use hard coded `/opt/rocm-$version` paths now and it would be unwise to manually git patch around that. We should just adopt this into the current project to make maintenance easier long term.

**Comment by acxz** [comment]
Ahh you're right, seems like we need to make some changes in our pkgbuilds then. Let's use this issue to keep a checklist of which packages need to be changed.

**Comment by cdarken** [comment]
Could this be the reason why OpenCL fails? Maybe it's looking for the OpenCL compiler in a versioned path?

**Comment by ranisalt** [comment]
I am strongly against this. Unless there's very compelling reason for users to have multiple versions installed for ROCm tools, this will only lead to confusion.

Also, that would imply that we maintain every single version as a separate package e.g. `rocm-opencl-stable`, `rocm-opencl-330`, `rocm-opencl-310` and so on, otherwise versioned directories make no sense at all.

Removing the version can be accomplished simply by running
```sh
rename -- "-$pkgver" '' "$pkgdir/opt/rocm-$pkgver"
```
As `hsa-ext-rocr` and `hsa-amd-aqlprofile` currently do.

**Comment by acxz** [comment]
Everything should be symlinked properly to /opt/rocm. 

I think it is important to follow upstream and if they are messing up then submitting patches there. I would rather we do that so that users can follow upstream documentation as much as possible instead of figuring out Arch does it.

It does not imply we maintain different versions at all. We will stick with providing the latest working packages.

**Comment by ranisalt** [comment]
> if they are messing up then submitting patches there

They do it because it is the Debian way. You can install any given version of some software on Debian, because dependencies are version locked. It does not make sense with Arch Linux and always-up-to-date versioning.

It's just a matter of seeing that version suffix is dropped, it's not a big deal for users.

How do you suggest we maintain partial upgrades when ROCm launches a new version and we need to update everything? What package would maintain the symlinking? Not everyone has the entire stack installed, for that matter.

**Comment by acxz** [comment]
We update things as we can, If some package build is broken then we leave it at that version, until we can fix it. The symlinking should be done on a package to package basis.

**Comment by ranisalt** [comment]
I can only see that being cumbersome, it's really not needed with Arch. Also, I understand the documentation says single instance is fine, multi instance is an option for whoever needs to use multiple versions at the same time (and I repeat, not needed with Arch).

They argue:
> - The new multi-instance package enables you to install two versions of the ROCm toolkit simultaneously and provides the ability to toggle between the two versioned packages.
So what's the point of providing such ability if we are not to provide two versions of the packages? Pointless.

The documentation states
> - The ROCm-DEV package does not create symlinks
>  - Users must create symlinks if required
And a couple lines below, the image states `symlink created by rocm-dev`. So it seems to me not even upstream is 100% sure on how that works currently.

**Comment by acxz** [comment]
After coming back to this conversation I actually agree with @ranisalt. Reading this convo again @ranisalt's side makes much more sense, esp considering the constantly updating that we are doing. While following upstream makes sense, (consistent) versioned install path is something that just we cannot follow with our current model of development for the foreseeable future.

Also considering no work has been done on this issue, I assume no one wants to do it anyway/there is not enough of an interest and am closing this issue thread.
