### ISSUE TITLE
[rocm-opencl-runtime] add support for gfx800s

### ISSUE THREAD

**Issue by John-Gee** [rocm-arch/rocm-arch#741]
Hello,

Until AMD accepts to readd Polaris support, would it be acceptable to add the patch from https://github.com/RadeonOpenCompute/ROCm/issues/1659 to do so?

Thank you!

rel com: https://github.com/RadeonOpenCompute/ROCm/issues/1659#issuecomment-1041026624

**Comment by acxz** [comment]
Usually we try our best to maintain as close to upstream as possible so that issues that show up for users on Arch can be considered valid issues for upstream ROCm repos. i.e. I don't want users facing issues here complaining to ROCm for what we have done uniquely. That creates a bad image for archlinux users to the AMD folks, which I would like to avoid.

That being said, reading through the issue it seems that there is quite a lot of support for this and the patch itself is just switching a boolean. In lieu of this, I would support a PR that adds support for gfx8** cards.

**Comment by John-Gee** [comment]
It's definitely a fair rule to keep as close as possible to upstream, but as you wrote it's just a boolean, so for those that didn't have it working it shouldn't be much worse, and hopefully it won't impact others.

If you're ok with a PR, I'll create one then. Thanks!

**Comment by John-Gee** [comment]
Done with #742 

Thank you!

**Comment by acxz** [comment]
@John-Gee we keep our issues open that are patched, so we know we are different from AMD.

**Comment by John-Gee** [comment]
My apologies!

**Comment by acxz** [comment]
@tpkessler is there any reason why the enhancement label was removed?

**Comment by tpkessler** [comment]
My reasoning was that an enhancement cannot be patched :)

**Comment by acxz** [comment]
I think I would consider this a patch since it changes the AMD codebase, as well as an enhancement as we are adding a feature that AMD is not.

It's a feature patch ;)

**Comment by John-Gee** [comment]
So it seems the patch may not be needed anymore, the variable ROC_ENABLE_PRE_VEGA=1 can do it instead. I verified that it works on my computer but only rebuilt this package. I'll create another PR to undo this and then maybe add the info to the wiki?

Thanks!
