### ISSUE TITLE
[rocblas] build error: use of undeclared identifier 'noinline'

### ISSUE THREAD

**Issue by JLague** [rocm-arch/rocm-arch#780]
When building rocblas-5.1.1-2 (specifically Tensile), I get `error: use of undeclared identifier 'noinline'`. The build was started in a chroot with `paru --chroot -S rocm-hip-sdk rocm-opencl-sdk`.

This issue is possibly related to the rocblas error mentioned in #777, although I don't know if it's the same error as @t1nux.

[rocblas build output](https://github.com/rocm-arch/rocm-arch/files/8691727/rocblas_build.txt)

**Comment by grinness** [comment]
Hi,

Same error here, using yay instead of paru.

error snippets when building tensile `Tensile/Source/lib/include/Tensile/EmbeddedData.hpp:30:`:

`In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/shared_ptr.h:53:
/usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/shared_ptr_base.h:196:22: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
      __attribute__((__noinline__))
                     ^
/opt/rocm/hip/include/hip/amd_detail/host_defines.h:50:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
`

`In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/memory:77:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/shared_ptr.h:53:
/usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/shared_ptr_base.h:196:22: error: type name does not allow function specifier to be specified
/opt/rocm/hip/include/hip/amd_detail/host_defines.h:50:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))`

'In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/memory:77:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/shared_ptr.h:53:
/usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/shared_ptr_base.h:196:22: error: expected expression
/opt/rocm/hip/include/hip/amd_detail/host_defines.h:50:46: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
'

**Comment by t1nux** [comment]
@JLague It's this issue exactly. Thanks for reporting, I didn't have time last week to do it!

**Comment by tpkessler** [comment]
Hey! I fixed this issue with https://github.com/rocm-arch/rocm-arch/commit/bffaf315960589541ca093671fa389ce9c9d365b. The problem was that HIP defines `__noinline__` but his is also defined in gcc, causing above issue.

**Comment by grinness** [comment]
Hey,

rocblas 5.1.3 now compiles

Thanks!

**Comment by tpkessler** [comment]
Great! I will close this issue then.

**Comment by FCLC** [comment]
this seems to still be an issue in 5.2.1 when targeting gfx1010

```
~/amd/rocm/build/rocm-build/build/rocblas$ ninja -j1 -k1
[0/2] Re-checking globbed directories...
[2/226] Building CXX object Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipSolutionAdapter.cpp.o
FAILED: Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipSolutionAdapter.cpp.o 
/opt/rocm/bin/hipcc -DTENSILE_DEFAULT_SERIALIZATION -DTENSILE_MSGPACK=1 -DTENSILE_USE_HIP -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/include -D__HIP_HCC_COMPAT_MODE__=1 -O3 -DNDEBUG -fPIC -Wno-unused-result -x hip --offload-arch=gfx1010 -std=c++14 -MD -MT Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipSolutionAdapter.cpp.o -MF Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipSolutionAdapter.cpp.o.d -o Tensile/lib/CMakeFiles/TensileHost.dir/source/hip/HipSolutionAdapter.cpp.o -c /home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/source/hip/HipSolutionAdapter.cpp
In file included from /home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/source/hip/HipSolutionAdapter.cpp:33:
In file included from /home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/include/Tensile/EmbeddedData.hpp:30:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
      __attribute__((__noinline__))
                     ^
/opt/rocm/include/hip/amd_detail/host_defines.h:50:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                    ^
In file included from /home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/source/hip/HipSolutionAdapter.cpp:33:
In file included from /home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/include/Tensile/EmbeddedData.hpp:30:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: type name does not allow function specifier to be specified
/opt/rocm/include/hip/amd_detail/host_defines.h:50:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                    ^
In file included from /home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/source/hip/HipSolutionAdapter.cpp:33:
In file included from /home/felix/amd/rocm/build/rocm-build/build/rocblas/virtualenv/lib/python3.10/site-packages/Tensile/Source/lib/include/Tensile/EmbeddedData.hpp:30:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:77:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr.h:53:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/shared_ptr_base.h:196:22: error: expected expression
/opt/rocm/include/hip/amd_detail/host_defines.h:50:46: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                             ^
3 errors generated when compiling for gfx1010.
ninja: build stopped: subcommand failed.
```
