### ISSUE TITLE
Cannot run python-pytorch-rocm (Assertion '__n < this->size()' failed)

### ISSUE THREAD

**Issue by FranGamer1892** [rocm-arch/rocm-arch#968]
### Discussed in https://github.com/orgs/rocm-arch/discussions/967

<div type='discussions-op-text'>

<sup>Originally posted by **FranGamer1892** July 28, 2023</sup>
Hello, after installing python-pytorch-rocm in a new Arch Linux installation, I noticed that I cannot run my pytorch-powered scripts as usual. For example, the following [python script](https://paste.debian.net/hidden/017c80c9), outputs [this](https://paste.debian.net/hidden/3610305f), followed by a video card glitch. This is my [rocminfo output](https://paste.debian.net/hidden/abe17a92). I find this weird since on my old Arch, everything (including this script) would work with no issues. Any help would be greatly appreciated. Thanks!</div>

I am turning this into an issue because I am beginning to run into this error on multiple clean Arch Linux installs and I am not sure why. Sometimes, instead of getting that error I just get "Segmentation fault". Looking at older issues, this might have to do with how the package is built. Please correct me if I am wrong. Thanks!

**Comment by acxz** [comment]
Considering this issue is directly related to the [python-pytorch](https://archlinux.org/packages/extra/x86_64/python-pytorch/) package, you should open a bug report on the Arch Linux package website: https://bugs.archlinux.org/?project=1&string=python-pytorch

It is fine to keep the discussion open, but this issue is not related to any PKGBUILDs located in this repo.

**Comment by FranGamer1892** [comment]
My apologies, I thought the package was still being maintained here even though it is not in the AUR anymore.
